#!/bin/bash
# Creates one schema + one scoped user per service (database-per-service on a single MySQL).
# Passwords come from the compose environment; they are local-dev credentials only.
set -e
mysql -u root -p"$MYSQL_ROOT_PASSWORD" <<-EOSQL
    CREATE SCHEMA IF NOT EXISTS $AUTH_DB_NAME;
    CREATE SCHEMA IF NOT EXISTS $MAIL_DB_NAME;
    CREATE SCHEMA IF NOT EXISTS $NOTIFICATION_DB_NAME;

    CREATE USER IF NOT EXISTS '$AUTH_DB_USER'@'%' IDENTIFIED BY '$AUTH_DB_PASSWORD';
    CREATE USER IF NOT EXISTS '$MAIL_DB_USER'@'%' IDENTIFIED BY '$MAIL_DB_PASSWORD';
    CREATE USER IF NOT EXISTS '$NOTIFICATION_DB_USER'@'%' IDENTIFIED BY '$NOTIFICATION_DB_PASSWORD';

    GRANT ALL PRIVILEGES ON $AUTH_DB_NAME.* TO '$AUTH_DB_USER'@'%';
    GRANT ALL PRIVILEGES ON $MAIL_DB_NAME.* TO '$MAIL_DB_USER'@'%';
    GRANT ALL PRIVILEGES ON $NOTIFICATION_DB_NAME.* TO '$NOTIFICATION_DB_USER'@'%';
    FLUSH PRIVILEGES;
EOSQL