#Overriding only the two lines that are different locally. Everything else is still read from `application.properties`.
spring.datasource.url=jdbc:mysql://localhost:3306/${DB_NAME}?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
cors.allowed.origin=http://localhost:8080